// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwhmqlmjqdwuuovwcjhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aG1xbG1qcWR3dXVvdndjamhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NTMzNjksImV4cCI6MjA2MzUyOTM2OX0.AKHzy0d-MVTl6VoyNQKnnh0RFsdv6gsm-koehcLgcxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);